// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LogisticsPro_Data.Models
{
    public partial class DB_LogisticsproContext : DbContext
    {
        public static string ConnectionString { get; set; }
        public DB_LogisticsproContext()
        {
            Database.SetCommandTimeout(ConfigurationValues.DATABASE_TIMEOUT);
        }

        public DB_LogisticsproContext(DbContextOptions<DB_LogisticsproContext> options)
            : base(options)
        {
        }

        public virtual DbSet<LpFInvoice> LpFInvoice { get; set; }
        public virtual DbSet<LpFInvoiceLineItem> LpFInvoiceLineItem { get; set; }
        public virtual DbSet<LpFInvoiceProformaInvoice> LpFInvoiceProformaInvoice { get; set; }
        public virtual DbSet<LpFPaymentVoucher> LpFPaymentVoucher { get; set; }
        public virtual DbSet<LpFPaymentVoucherLineItem> LpFPaymentVoucherLineItem { get; set; }
        public virtual DbSet<LpFProformaInvoice> LpFProformaInvoice { get; set; }
        public virtual DbSet<LpFProformaInvoiceReceipt> LpFProformaInvoiceReceipt { get; set; }
        public virtual DbSet<LpFReceipt> LpFReceipt { get; set; }
        public virtual DbSet<LpFReceiptAllocation> LpFReceiptAllocation { get; set; }
        public virtual DbSet<LpJFinancePayment> LpJFinancePayment { get; set; }
        public virtual DbSet<LpJFinanceReceipt> LpJFinanceReceipt { get; set; }
        public virtual DbSet<LpJHotel> LpJHotel { get; set; }
        public virtual DbSet<LpJHotelAudit> LpJHotelAudit { get; set; }
        public virtual DbSet<LpJMiscellaneous> LpJMiscellaneous { get; set; }
        public virtual DbSet<LpJMiscellaneousAudit> LpJMiscellaneousAudit { get; set; }
        public virtual DbSet<LpJTransportation> LpJTransportation { get; set; }
        public virtual DbSet<LpJTransportationAudit> LpJTransportationAudit { get; set; }
        public virtual DbSet<LpJVisa> LpJVisa { get; set; }
        public virtual DbSet<LpJVisaAudit> LpJVisaAudit { get; set; }
        public virtual DbSet<LpJobCard> LpJobCard { get; set; }
        public virtual DbSet<LpJobCardAudit> LpJobCardAudit { get; set; }
        public virtual DbSet<LpLBatch> LpLBatch { get; set; }
        public virtual DbSet<LpLBatchLineItem> LpLBatchLineItem { get; set; }
        public virtual DbSet<LpMCounrty> LpMCounrty { get; set; }
        public virtual DbSet<LpMCustomer> LpMCustomer { get; set; }
        public virtual DbSet<LpMEvent> LpMEvent { get; set; }
        public virtual DbSet<LpMInvoiceStatus> LpMInvoiceStatus { get; set; }
        public virtual DbSet<LpMPaymentMethod> LpMPaymentMethod { get; set; }
        public virtual DbSet<LpMStatus> LpMStatus { get; set; }
        public virtual DbSet<LpMSystemRole> LpMSystemRole { get; set; }
        public virtual DbSet<LpMTransactionType> LpMTransactionType { get; set; }
        public virtual DbSet<LpMUser> LpMUser { get; set; }
        public virtual DbSet<LpMVender> LpMVender { get; set; }
        public virtual DbSet<LpMVisaType> LpMVisaType { get; set; }
        public virtual DbSet<LpSystemConfig> LpSystemConfig { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<LpFInvoice>(entity =>
            {
                entity.ToTable("LP_F_Invoice");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.InvoiceCode).HasMaxLength(50);

                entity.Property(e => e.InvoiceDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceDueDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpFInvoiceLineItem>(entity =>
            {
                entity.ToTable("LP_F_InvoiceLineItem");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpFInvoiceProformaInvoice>(entity =>
            {
                entity.ToTable("LP_F_Invoice_ProformaInvoice");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpFPaymentVoucher>(entity =>
            {
                entity.ToTable("LP_F_PaymentVoucher");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceNo).HasMaxLength(50);

                entity.Property(e => e.PaymentVoucherCode).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.VoucherAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.VoucherDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpFPaymentVoucherLineItem>(entity =>
            {
                entity.ToTable("LP_F_PaymentVoucherLineItem");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpFProformaInvoice>(entity =>
            {
                entity.ToTable("LP_F_ProformaInvoice");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.InvoiceCode).HasMaxLength(50);

                entity.Property(e => e.InvoiceDate).HasColumnType("datetime");

                entity.Property(e => e.InvoiceDueDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpFProformaInvoiceReceipt>(entity =>
            {
                entity.ToTable("LP_F_ProformaInvoiceReceipt");

                entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.IsAllocatedToInvoice).HasDefaultValueSql("((0))");

                entity.Property(e => e.PaymentDate).HasColumnType("datetime");

                entity.Property(e => e.ReceiptCode).HasMaxLength(50);

                entity.Property(e => e.Remark).HasMaxLength(200);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpFReceipt>(entity =>
            {
                entity.ToTable("LP_F_Receipt");

                entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.IsAllocated).HasDefaultValueSql("((0))");

                entity.Property(e => e.PaymentDate).HasColumnType("datetime");

                entity.Property(e => e.ReceiptCode).HasMaxLength(50);

                entity.Property(e => e.Remark).HasMaxLength(200);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpFReceiptAllocation>(entity =>
            {
                entity.ToTable("LP_F_ReceiptAllocation");

                entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpJFinancePayment>(entity =>
            {
                entity.ToTable("LP_J_FinancePayment");

                entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.FinanceCode).HasMaxLength(50);

                entity.Property(e => e.InvoiceNo).HasMaxLength(50);

                entity.Property(e => e.TransactionDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.VoucherNo).HasMaxLength(50);
            });

            modelBuilder.Entity<LpJFinanceReceipt>(entity =>
            {
                entity.ToTable("LP_J_FinanceReceipt");

                entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.FinanceCode).HasMaxLength(50);

                entity.Property(e => e.InvoiceNo).HasMaxLength(50);

                entity.Property(e => e.TransactionDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpJHotel>(entity =>
            {
                entity.ToTable("LP_J_Hotel");

                entity.HasIndex(e => e.CheckIn, "NonClusteredIndex-LP_J_Hotel_CheckingTime");

                entity.HasIndex(e => e.JobCardId, "NonClusteredIndex-LP_J_Hotel_JobCardId");

                entity.Property(e => e.CheckIn).HasColumnType("datetime");

                entity.Property(e => e.CheckOut).HasColumnType("datetime");

                entity.Property(e => e.CostBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CostTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.HotelCode).HasMaxLength(50);

                entity.Property(e => e.HotelConfirmation).HasMaxLength(100);

                entity.Property(e => e.HotelName).HasMaxLength(100);

                entity.Property(e => e.IsInvoiced).HasDefaultValueSql("((0))");

                entity.Property(e => e.IsPaymentVouchered).HasDefaultValueSql("((0))");

                entity.Property(e => e.RoomType).HasMaxLength(100);

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpJHotelAudit>(entity =>
            {
                entity.HasKey(e => e.AuditId);

                entity.ToTable("LP_J_Hotel_Audit");

                entity.Property(e => e.AuditAction).HasMaxLength(10);

                entity.Property(e => e.AuditDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CheckIn).HasColumnType("datetime");

                entity.Property(e => e.CheckOut).HasColumnType("datetime");

                entity.Property(e => e.CostBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CostTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.HotelCode).HasMaxLength(50);

                entity.Property(e => e.HotelConfirmation).HasMaxLength(100);

                entity.Property(e => e.HotelName).HasMaxLength(100);

                entity.Property(e => e.RoomType).HasMaxLength(100);

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpJMiscellaneous>(entity =>
            {
                entity.ToTable("LP_J_Miscellaneous");

                entity.HasIndex(e => e.JobCardId, "NonClusteredIndex-LP_J_Miscellaneous_JobCardId");

                entity.HasIndex(e => e.MisDate, "NonClusteredIndex-LP_J_Miscellaneous_MiscDate");

                entity.Property(e => e.CostBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CostTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.IsFinance).HasDefaultValueSql("((0))");

                entity.Property(e => e.IsInvoiced).HasDefaultValueSql("((0))");

                entity.Property(e => e.IsPaymentVouchered).HasDefaultValueSql("((0))");

                entity.Property(e => e.MisDate).HasColumnType("datetime");

                entity.Property(e => e.MiscellaneousCode).HasMaxLength(50);

                entity.Property(e => e.PaxNumber).HasMaxLength(100);

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpJMiscellaneousAudit>(entity =>
            {
                entity.HasKey(e => e.AuditId);

                entity.ToTable("LP_J_Miscellaneous_Audit");

                entity.Property(e => e.AuditAction).HasMaxLength(10);

                entity.Property(e => e.AuditDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CostBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CostTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.MisDate).HasColumnType("datetime");

                entity.Property(e => e.MiscellaneousCode).HasMaxLength(50);

                entity.Property(e => e.PaxNumber).HasMaxLength(100);

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpJTransportation>(entity =>
            {
                entity.ToTable("LP_J_Transportation");

                entity.HasIndex(e => e.JobCardId, "NonClusteredIndex-LP_J_Transportation_JobCardId");

                entity.HasIndex(e => e.PickupTime, "NonClusteredIndex-LP_J_Transportation_PickupTime");

                entity.Property(e => e.CostBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CostTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerRef).HasMaxLength(100);

                entity.Property(e => e.DropoffLocation).HasMaxLength(100);

                entity.Property(e => e.Extras).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ExtrasSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ExtrasTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ExtrasTaxAmountSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.FlightNo).HasMaxLength(100);

                entity.Property(e => e.FlightTime).HasColumnType("datetime");

                entity.Property(e => e.IsInvoiced).HasDefaultValueSql("((0))");

                entity.Property(e => e.IsPaymentVouchered).HasDefaultValueSql("((0))");

                entity.Property(e => e.Parking).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ParkingSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ParkingTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ParkingTaxAmountSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.PickupLocation).HasMaxLength(100);

                entity.Property(e => e.PickupTime).HasColumnType("datetime");

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.TransportationCode).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.VehicleType).HasMaxLength(100);

                entity.Property(e => e.Water).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WaterSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WaterTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WaterTaxAmountSell).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<LpJTransportationAudit>(entity =>
            {
                entity.HasKey(e => e.AuditId);

                entity.ToTable("LP_J_Transportation_Audit");

                entity.Property(e => e.AuditAction).HasMaxLength(10);

                entity.Property(e => e.AuditDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CostBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CostTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerRef).HasMaxLength(100);

                entity.Property(e => e.DropoffLocation).HasMaxLength(100);

                entity.Property(e => e.Extras).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ExtrasSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ExtrasTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ExtrasTaxAmountSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.FlightNo).HasMaxLength(100);

                entity.Property(e => e.FlightTime).HasColumnType("datetime");

                entity.Property(e => e.Parking).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ParkingSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ParkingTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.ParkingTaxAmountSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.PickupLocation).HasMaxLength(100);

                entity.Property(e => e.PickupTime).HasColumnType("datetime");

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.TransportationCode).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.VehicleType).HasMaxLength(100);

                entity.Property(e => e.Water).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WaterSell).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WaterTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.WaterTaxAmountSell).HasColumnType("decimal(18, 2)");
            });

            modelBuilder.Entity<LpJVisa>(entity =>
            {
                entity.ToTable("LP_J_Visa");

                entity.HasIndex(e => e.JobCardId, "NonClusteredIndex-LP_J_Visa_JobCardId");

                entity.HasIndex(e => e.CreatedDate, "NonClusteredIndex-LP_J_Visa_VisaCreateDate");

                entity.Property(e => e.CostBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CostTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.IsInvoiced).HasDefaultValueSql("((0))");

                entity.Property(e => e.IsPaymentVouchered).HasDefaultValueSql("((0))");

                entity.Property(e => e.PassportNo).HasMaxLength(100);

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.VisaCode).HasMaxLength(50);
            });

            modelBuilder.Entity<LpJVisaAudit>(entity =>
            {
                entity.HasKey(e => e.AuditId);

                entity.ToTable("LP_J_Visa_Audit");

                entity.Property(e => e.AuditAction).HasMaxLength(10);

                entity.Property(e => e.AuditDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CostBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CostTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.PassportNo).HasMaxLength(100);

                entity.Property(e => e.SellBaseAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.SellTaxAmount).HasColumnType("decimal(18, 2)");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.VisaCode).HasMaxLength(50);
            });

            modelBuilder.Entity<LpJobCard>(entity =>
            {
                entity.ToTable("LP_JobCard");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerRef).HasMaxLength(200);

                entity.Property(e => e.EffectiveDate).HasColumnType("datetime");

                entity.Property(e => e.JobCardCode).HasMaxLength(50);

                entity.Property(e => e.Remarks).HasColumnType("text");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpJobCardAudit>(entity =>
            {
                entity.HasKey(e => e.AuditId);

                entity.ToTable("LP_JobCard_Audit");

                entity.Property(e => e.AuditAction).HasMaxLength(10);

                entity.Property(e => e.AuditDate)
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerRef).HasMaxLength(200);

                entity.Property(e => e.EffectiveDate).HasColumnType("datetime");

                entity.Property(e => e.JobCardCode).HasMaxLength(50);

                entity.Property(e => e.Remarks).HasColumnType("text");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpLBatch>(entity =>
            {
                entity.ToTable("LP_L_Batch");

                entity.Property(e => e.BatchCode).HasMaxLength(50);

                entity.Property(e => e.BatchDate).HasColumnType("datetime");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpLBatchLineItem>(entity =>
            {
                entity.ToTable("LP_L_BatchLineItem");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMCounrty>(entity =>
            {
                entity.ToTable("LP_M_Counrty");

                entity.Property(e => e.CounrtyName).HasMaxLength(50);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMCustomer>(entity =>
            {
                entity.ToTable("LP_M_Customer");

                entity.Property(e => e.Address1).HasMaxLength(500);

                entity.Property(e => e.Address2).HasMaxLength(500);

                entity.Property(e => e.City).HasMaxLength(50);

                entity.Property(e => e.ContactNumber).HasMaxLength(50);

                entity.Property(e => e.ContactPersonName).HasMaxLength(400);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.CustomerCode)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.CustomerName)
                    .IsRequired()
                    .HasMaxLength(400);

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Trn).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMEvent>(entity =>
            {
                entity.ToTable("LP_M_Event");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.EventFromDate).HasColumnType("datetime");

                entity.Property(e => e.EventName).HasMaxLength(200);

                entity.Property(e => e.EventToDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMInvoiceStatus>(entity =>
            {
                entity.ToTable("LP_M_InvoiceStatus");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.StatusName).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMPaymentMethod>(entity =>
            {
                entity.ToTable("LP_M_PaymentMethod");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.PaymentMethodName).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMStatus>(entity =>
            {
                entity.ToTable("LP_M_Status");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.StatusName).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMSystemRole>(entity =>
            {
                entity.ToTable("LP_M_SystemRole");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.RoleName).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMTransactionType>(entity =>
            {
                entity.ToTable("LP_M_TransactionType");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.TransactionTypeName).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            modelBuilder.Entity<LpMUser>(entity =>
            {
                entity.ToTable("LP_M_User");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.LastLoginDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.UserName).HasMaxLength(50);
            });

            modelBuilder.Entity<LpMVender>(entity =>
            {
                entity.ToTable("LP_M_Vender");

                entity.Property(e => e.Address1).HasMaxLength(500);

                entity.Property(e => e.Address2).HasMaxLength(500);

                entity.Property(e => e.BankBranch).HasMaxLength(50);

                entity.Property(e => e.BankCode).HasMaxLength(50);

                entity.Property(e => e.BankName).HasMaxLength(50);

                entity.Property(e => e.City).HasMaxLength(50);

                entity.Property(e => e.ContactNumber).HasMaxLength(50);

                entity.Property(e => e.ContactPersonName).HasMaxLength(400);

                entity.Property(e => e.CountryCode).HasMaxLength(50);

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.Iban).HasMaxLength(50);

                entity.Property(e => e.SwiftCode).HasMaxLength(50);

                entity.Property(e => e.Trn).HasMaxLength(50);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.VenderCode)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.VenderName)
                    .IsRequired()
                    .HasMaxLength(400);

                entity.Property(e => e.VendorTypeIds).HasMaxLength(50);
            });

            modelBuilder.Entity<LpMVisaType>(entity =>
            {
                entity.ToTable("LP_M_VisaType");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

                entity.Property(e => e.VisaTypeName).HasMaxLength(50);
            });

            modelBuilder.Entity<LpSystemConfig>(entity =>
            {
                entity.ToTable("LP_SystemConfig");

                entity.Property(e => e.CreatedDate).HasColumnType("datetime");

                entity.Property(e => e.SystemCode).HasMaxLength(100);

                entity.Property(e => e.UpdatedDate).HasColumnType("datetime");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}