// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogisticsPro_Data.Models
{
    public partial class LpFReceiptAllocation
    {
        public int Id { get; set; }
        public int? ReceiptId { get; set; }
        public int? InvoiceId { get; set; }
        public int? ContextId { get; set; }
        public int? ContextTypeId { get; set; }
        public decimal? Amount { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}