// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogisticsPro_Data.Models
{
    public partial class LpJFinancePayment
    {
        public int Id { get; set; }
        public string FinanceCode { get; set; }
        public int? JobCardId { get; set; }
        public int? VendorId { get; set; }
        public string InvoiceNo { get; set; }
        public string VoucherNo { get; set; }
        public decimal? Amount { get; set; }
        public DateTime? TransactionDate { get; set; }
        public string Remarks { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}