// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogisticsPro_Data.Models
{
    public partial class LpJMiscellaneousAudit
    {
        public int AuditId { get; set; }
        public int? Id { get; set; }
        public string MiscellaneousCode { get; set; }
        public int? JobCardId { get; set; }
        public string PaxName { get; set; }
        public string PaxNumber { get; set; }
        public string Description { get; set; }
        public DateTime? MisDate { get; set; }
        public bool? IsVatIncludedCost { get; set; }
        public decimal? CostBaseAmount { get; set; }
        public decimal? CostTaxAmount { get; set; }
        public bool? IsVatIncludedSell { get; set; }
        public decimal? SellBaseAmount { get; set; }
        public decimal? SellTaxAmount { get; set; }
        public string Remarks { get; set; }
        public int? VendorId { get; set; }
        public bool? IsPaymentVouchered { get; set; }
        public bool? IsInvoiced { get; set; }
        public bool? IsFinance { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string AuditAction { get; set; }
        public DateTime? AuditDate { get; set; }
    }
}