// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogisticsPro_Data.Models
{
    public partial class LpFProformaInvoice
    {
        public int Id { get; set; }
        public string InvoiceCode { get; set; }
        public int? CustomerId { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public DateTime? InvoiceDueDate { get; set; }
        public decimal? InvoiceAmount { get; set; }
        public int? JobCardId { get; set; }
        public string Description { get; set; }
        public int? StatusId { get; set; }
        public bool? IsAllocatedToInvoice { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}