// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogisticsPro_Data.Models
{
    public partial class LpFPaymentVoucher
    {
        public int Id { get; set; }
        public string PaymentVoucherCode { get; set; }
        public int? VendorId { get; set; }
        public DateTime? VoucherDate { get; set; }
        public string InvoiceNo { get; set; }
        public decimal? VoucherAmount { get; set; }
        public string Remark { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}