// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogisticsPro_Data.Models
{
    public partial class LpFReceipt
    {
        public int Id { get; set; }
        public string ReceiptCode { get; set; }
        public int? InvoiceId { get; set; }
        public decimal? Amount { get; set; }
        public int? PaymentMethodId { get; set; }
        public string Remark { get; set; }
        public DateTime? PaymentDate { get; set; }
        public bool? IsAllocated { get; set; }
        public bool? IsVoid { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}