// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LogisticsPro_Data.Models
{
    public partial class LpJobCard
    {
        public int Id { get; set; }
        public string JobCardCode { get; set; }
        public string JobDescription { get; set; }
        public int? CustomerId { get; set; }
        public string CustomerRef { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public string Remarks { get; set; }
        public int? StatusId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}